accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('list/', views.AccountListView.as_view(), name='list'),
    path('add/', views.AccountCreateView.as_view(), name='new'),
]

seedstars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models


class Account(models.Model):
    """Represents account entry name/email"""
    name = models.CharField(max_length=255)
    email = models.EmailField()

    def __str__(self):
        return self.name

accounts/forms.py
from django.forms import ModelForm

from .models import Account


class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'email']

accounts/views.py
from django.views import generic
from django.urls import reverse_lazy

from .forms import AccountForm
from .models import Account


class HomePageView(generic.TemplateView):
    template_name = 'accounts/home.html'


class AccountListView(generic.ListView):
    model = Account
    context_object_name = 'accounts_list'
    template_name = 'accounts/account_list.html'


class AccountCreateView(generic.CreateView):
    form_class = AccountForm
    template_name = 'accounts/account_form.html'
    success_url = reverse_lazy('accounts:list')

accounts/templates/accounts/account_form.html
{% extends 'accounts/base.html' %}

{% block title %}Create Account{% endblock %}

{% block content %}
    <form method="POST" class="account-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save">Create!</button>
    </form>
{% endblock %}

accounts/templates/accounts/account_list.html
{% extends 'accounts/base.html' %}

{% block title %}Accounts{% endblock %}

{% block content %}
    <div class="accounts">
        {% for account in accounts_list %}
            <div class="account">
                <p class="name">{{ account.name }}</p>
                <p class="email">{{ account.email }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">

    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <div class="navigation">
        <a href="{% url 'accounts:list' %}">Accounts List</a>
        <a href="{% url 'accounts:new' %}">Create new account.</a>
    </div>
{% endblock %}